name: GCAN-Flu
channels:
  - pyg
  - pytorch
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=12.1
  - pyg=2.4.0
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - numpy=1.24.3
  - scipy=1.10.1
  - matplotlib=3.7.2
  - tqdm=4.65.0
  - pyyaml=6.0.1
  - pip
  - pip:
    - openpyxl==3.1.5
    - pyg-lib==0.3.1+pt21cu121